apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bertobert-bertobert-poi-map-app-dev
  annotations:
    argocd/app-name: bertobert-bertobert-poi-map-app-dev
    backstage.io/kubernetes-id: bertobert-bertobert-poi-map-app-dev
    backstage.io/kubernetes-namespace: bertobert
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=bertobert-bertobert-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/bertobert-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/bertobert/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/bertobert/deployments/bertobert-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/bertobert-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://bertobert-poi-map-app-bertobert.apps.summit23rock.n26o.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/bertobert"
  system: workshop-system-bertobert
  consumesApis:
    - gateway-api-bertobert
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-bertobert
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/bertobert"
